service:
  name: todo-list

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"

functions:
  createTodo: 
    handler: src/functions/create-todo.handle
    events:
      - http:
          path: /todos/{userId}
          method: POST
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action: 
          - dynamodb:PutItem
  
  listTodos: 
    handler: src/functions/list-todos.handle
    events:
      - http:
          path: /todos/{userId}
          method: get
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action: 
          - dynamodb:Query

resources:
  Resources:
    todos:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: todos
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
